### ISSUE TITLE
Outdated stable version

### ISSUE THREAD

**Issue by MUlt1mate** [mtdowling/cron-expression#100]
The last stable version v1.0.4 has at least one bug: 
Some expressions not recognized (```0 0 1 * *```, ```0 0 1 1 *```). Works fine in master though. 
I have a project that has dependency from this package. But I don't want to use dev-master version of your project, because it can be broken in future commits. Can you please release new stable version? Thanks.

**Comment by MUlt1mate** [comment]
Is anybody alive in here?

**Comment by dragonmantank** [comment]
We are :) I've recently taken over maintenance of the project, so getting
my ducks in a row in regards to existing issues and tickets.

On Saturday, January 23, 2016, Mikhail <notifications@github.com> wrote:

> Is anybody alive in here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtdowling/cron-expression/issues/100#issuecomment-174170563>
> .
>


-- 
Chris Tankersley
http://ctankersley.com

**Comment by dragonmantank** [comment]
@MUlt1mate Just FYI, I'm looking at pushing out a v1.1.0 update here soon. Most of it is bug fixes, but there are some new additions like non-hourly offsets for timezones.

**Comment by dragonmantank** [comment]
v1.1.0 has been pushed.

**Comment by MUlt1mate** [comment]
Thank you
