### ISSUE TITLE
 this plugin can be used to run on the Windows server ?

### ISSUE THREAD

**Issue by wakerman** [mtdowling/cron-expression#117]
Hello, this plugin can be used to run on the Windows server, such as 2003 or 2012 ?

Thanks.

**Comment by dragonmantank** [comment]
Technically it should, yes, as PHP and PHP's `DateTime` code works fine on Windows.

This library is meant to only parse a cron expression and give you a Yes/No answer as to whether the current time matches the expression. This library is _not_ a full cron system. You still need your application to actually do any work. 

Hope that helps!
