### ISSUE TITLE
Incorrect expression in blog post

### ISSUE THREAD

**Issue by DarkSide666** [mtdowling/cron-expression#119]
Expression `0 0 0 ? 1/2 FRI#2 *` in your blog post http://mtdowling.com/blog/2012/06/03/cron-expressions-in-php/ looks incorrect.
Correct one would be `0 0 * 1/2 FRI#2 *`.

**Comment by dragonmantank** [comment]
@mtdowling ^ 

Closing this since the library isn't directly attached to the @mtdowling's website.

**Comment by DarkSide666** [comment]
well ... of course it's not directly attached, but I believe that website blog post should be corrected if it cares about readers :)
