### ISSUE TITLE
[suggestion] every nth week

### ISSUE THREAD

**Issue by envomer** [mtdowling/cron-expression#123]
Is there the possibility to make something like this valid?
50 21 \* \* 0,2,3,4/2

This command would run at 21:50 on Sun, Tue, Wed, Thu every second week.

Do you think it's possible?

Apparently '0 6 \* \* Tue expr `date +\%W` \% 2' works on crontab but doesn't look so good.

Appreciate all the good work. Thanks 👍

**Comment by dragonmantank** [comment]
That's an interesting proposition. From the looks of things your hacky way with the date format is one of the few ways to get cron to actually accept an arbitrary date range, since `weeks` is not part of the cron format.

I'd like to keep this library as close to the actual cron format as possible, but I'll leave this open for input from other people and maybe consider it for the future.

**Comment by envomer** [comment]
I get what you mean. Thanks for leaving it open and your fast reply 👍 :fingers crossed:

**Comment by challgren** [comment]
This is actually a feature I require for my application. My intent is to allow customers to schedule campaigns such as first tuesday of every month. 

I would propose the format that follows quartz.

> `# - used to specify “the nth” XXX day of the month. For example, the value of “6#3” in the day-of-week field means “the third Friday of the month” (day 6 = Friday and “#3” = the 3rd one in the month). Other examples: “2#1” = the first Monday of the month and “4#5” = the fifth Wednesday of the month. Note that if you specify “#5” and there is not 5 of the given day-of-week in the month, then no firing will occur that month.`

http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

**Comment by challgren** [comment]
Also the README for this project states

>  hash (#) to find the nth weekday of a given month.

**Comment by jfrioux** [comment]
+1 for staying close to Cron syntax.

**Comment by dragonmantank** [comment]
Closing this issue. There's been no movement, and I'm still of the mind to stick as close to actual Cron (specifically cronie) behavior as possible
