### ISSUE TITLE
`Cron\CronExpression::isValidExpression('990 14 * * mon-fri0345345')` returns `true`

### ISSUE THREAD

**Issue by Sarke** [mtdowling/cron-expression#125]
`isValidExpression` only catches `InvalidArgumentException`, but for patterns such as `990 14 * * mon-fri0345345` factory will `throw new \RuntimeException('Impossible CRON expression');` instead.

Since this is not caught by `isValidExpression` it will return `true`.  It basically renders the function useless.

**Comment by Sarke** [comment]
Correction: it's `getRunDate()` that throws the `RuntimeException`.  So to get it working as intended, something like this would be needed:

    public static function isValidExpression($expression)
    {
        try {
            $cron = self::factory($expression);
			$cron->getNextRunDate();
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }

**Comment by dragonmantank** [comment]
This is coupled into a bunch of validation issues each of the fields have, so as the individual fields get updated this should hopefully resolve itself.

**Comment by dragonmantank** [comment]
Fixed in b9f4588 as part of the validation updates
