### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by prisis** [mtdowling/cron-expression#130]

**Comment by dragonmantank** [comment]
Yes, the project is still being maintained :)

There are some PRs which are open that I haven't looked at, but other than 1 potential bug that I haven't had a chance to compare to real cron, the package is pretty stable so there isn't a ton of active work on it.

**Comment by prisis** [comment]
Thx, for the answer :)

Hope you have some time to check this pr https://github.com/mtdowling/cron-expression/pull/115 is really helpful to set custom timezones 

Thx :)
