### ISSUE TITLE
Some string masks that are validated and should not

### ISSUE THREAD

**Issue by playmono** [mtdowling/cron-expression#141]
*-1 * * * *
1-2-3 * * * *
-1 * * * *

**Comment by dragonmantank** [comment]
Thanks for flagging these. I'm going to be going through all of the validation routines as the regex currently used are not really doing their job well.

**Comment by dragonmantank** [comment]
Corrected this with the new validation code and 6a81b0c9329b4d8bf2577c8f99fb804806735ff4

Thanks!
