### ISSUE TITLE
Tag updates

### ISSUE THREAD

**Issue by laurencei** [mtdowling/cron-expression#150]
Hi @dragonmantank ,

Any chance of "tagging" a new release v1.3?

There have been a few PRs accepted recently and it would be nice to be able to use those on a stable tagged version.

Thanks.

**Comment by laurencei** [comment]
Hi @dragonmantank / @mtdowling 

Any chance of a 1.3 tag please? All the recent PRs can be used on a stable tag at the moment.

Thanks in advance...

**Comment by dragonmantank** [comment]
@laurencei The validation and stepping issues I was working on for 2.0 have been introduced into master, and I am just sitting on them waiting for some testing. All the phpunit tests pass, but hopefully I can get some real-world testing before tagging it officially.

There will be no 1.3 tag though, the 1.x branch is no longer being maintained. Unfortunately there's too many bugs in the validation code for me to comfortably package a 1.3 tag, as the validation fixes introduce a bunch of backward compatibility issues for people that might be relying on the bugs.

**Comment by laurencei** [comment]
Ok mate - no dramas. Thanks for the awesome work on this package.

**Comment by dilab** [comment]
waiting for v2.:)

**Comment by dragonmantank** [comment]
2.x has been released over at https://github.com/dragonmantank/cron-expression with the latest fixes (more info available at http://ctankersley.com/2017/10/12/cron-expression-update/). If you are using this package with Laravel, I'll be working with them to get this updated in their next release.
