### ISSUE TITLE
Does v1.2.0 still have full PHP 5.3+ support?

### ISSUE THREAD

**Issue by chetcuti** [mtdowling/cron-expression#151]
I noticed that some of the recent updates are removing support for PHP v5 and will only support v7 going forward, but I wanted to confirm that v1.2.0 still has full support for PHP v5.3+.

I have PHP Cron Expression Parser included in an open source project of mine, and I want to upgrade from v1.1.0 to v1.2.0, but I can't do so if it's going to lose support for PHP v5.

**Comment by dragonmantank** [comment]
Yes, 1.2.x will continue to have PHP 5.x support. At this point I do not think there will be many more updates to that version though, as most of the fixes being worked on will break backward compatibility with the expressions that used to be allowed. 

It should be safe to upgrade from 1.1.0 to 1.2.0 though.
