### ISSUE TITLE
Class \Cron\YearField not found - Referenced in \Cron\FieldFactory

### ISSUE THREAD

**Issue by rthrfrd** [mtdowling/cron-expression#160]
https://github.com/mtdowling/cron-expression/blob/5c2852da3daf36c65e9d5f3fcde5887898d530d9/src/Cron/FieldFactory.php#L46

**Comment by dragonmantank** [comment]
Thanks, missed this when YearField was removed.

Call is removed in 56e89730e60a0e945bf4ea10c48b80a406c7e7a0
