### ISSUE TITLE
Not support PHP 7.1.9

### ISSUE THREAD

**Issue by vladkireev** [mtdowling/cron-expression#161]
PHP Warning 'yii\base\ErrorException' with message 'A non-numeric value encountered'
Stack trace:
#0 .../vendor/mtdowling/cron-expression/src/Cron/AbstractField.php(101): yii\base\ErrorHandler->handleError(2, 'A non-numeric v...', '/var/www/telegr...', 101, Array)
#1 .../vendor/mtdowling/cron-expression/src/Cron/AbstractField.php(21): Cron\AbstractField->isInIncrementsOfRanges('02', '/5')
#

http://php.net/manual/ru/migration71.other-changes.php

**Comment by dragonmantank** [comment]
Hello!

Can you let me know which version of the library you are running, and the full cron expression you were using? Thanks!

**Comment by vladkireev** [comment]
Hello! 
Version 1.2
Cron expression full : /5 * * * *

**Comment by vladkireev** [comment]
Version 1.0 support this version php (1.1 not support)

**Comment by dragonmantank** [comment]
Unfortunately the 1.x branch is not going to be maintained going forward, unless there is some sort of serious security issue (which I doubt, considering we're just evaluating numbers pretty much).

That being said, the above isn't a valid cron expression. Your `minute` field will need to provide a range value on the left-hand-side of the `/`. Most cron programs, and this library, will not default to anything. My guess is you want a `*` to denote the entire range, but you'll need to supply something there for it to work with.
