### ISSUE TITLE
dragonmantank repository: Unclear where to submit issues

### ISSUE THREAD

**Issue by AllenJB** [mtdowling/cron-expression#163]
The dragonmantank repository has issues disabled and there's no instructions on where issues should be submitted in the readme.

Either the dragonmantank repository should specify that the mtdowling issues section should be used in the readme, or it should have issues enabled itself.

**Comment by dragonmantank** [comment]
Just an oversight. I turned on issues there, but will gladly take a look at the new issue you posted here.
