### ISSUE TITLE
Composer Autoloader - Not Working (>= 1.6.0) 

### ISSUE THREAD

**Issue by laurin1** [mtdowling/cron-expression#166]
As of Composer 1.6.0, autoloader does not work. I've confirmed in Composer 1.5.6 and 1.6.0-RC, it works, but in 1.6.0, this fails to load.

https://github.com/composer/composer/compare/1.6.0-RC...1.6.0

"Class 'Cron\CronExpression' not found"

Using CronExpression 1.2.1.

**Comment by staabm** [comment]
1.6.1 was already released with a autoload tweek.. does this work for you?

**Comment by laurin1** [comment]
No, sorry - I should have said I tested all versions from 1.5.6 to 1.6.1 and the failure occurs in release 1.6.0.

**Comment by laurin1** [comment]
FYI, I have 2 packages failing:

https://github.com/PHPMailer/PHPMailer/issues/1316

**Comment by laurin1** [comment]
Oh, duh:

https://github.com/composer/composer/issues/6977

**Comment by dragonmantank** [comment]
Looks like Composer 1.6.2 should fix the issue. Thanks for bringing this to my attention!
