### ISSUE TITLE
Mark this as abandoned on packagist

### ISSUE THREAD

**Issue by SamMousa** [mtdowling/cron-expression#169]
Since this repo no longer sees any development (since it has continued in a different repo), it makes sense to mark the accompanying package as abandoned on packagist.

**Comment by GrahamCampbell** [comment]
Bump.

**Comment by dragonmantank** [comment]
Marked it as abandoned in `composer.json` as of v1.2.2. There's been enough time for both Laraval and others to switch over.

I cannot mark it directly in Packagist as abandoned hough, as this is a personal repo and I don't have access.

**Comment by tfettig** [comment]
Just for a PSA, I opened up #176 since the new 1.2.2 tag caught up some extra code from master that caused issues with Laravel 5.4.  I'm not expecting anything to be done here since all this stuff is old, but hopefully this will help someone who's stuck.

**Comment by dragonmantank** [comment]
Thanks! Will leave this issue open for a bit in case others stop by
looking.

**Comment by GrahamCampbell** [comment]
Looks like tagging 1.2.2 was a bug, and contains breaking changes. Maybe the tag should be deleted?

**Comment by GrahamCampbell** [comment]
> Marked it as abandoned in composer.json as of v1.2.2. 

That doesn't do anything I'm afraid. No machine will look at that. It must be done from the packagist UI.

**Comment by dragonmantank** [comment]
Deleted v1.2.2 and re-pushed as v1.2.3, I had forgotten that the master branch on here did have some of what ended up being v2. The bug should have gone away.

That being said, as I've mentioned before since this is a personal repo I cannot mark it abandoned in Packagist. I've requested that it be done so, but it haven't seen mtdowling do it yet. The best I can do is document it in the meantime.

**Comment by GrahamCampbell** [comment]
I don't understand why we need any new release after 1.2.1. Adding the abandoned flag into the composer.json doesn't do anything, since no machine ever looks at it. It doesn't have the affect of making it abandoned?

**Comment by dragonmantank** [comment]
It makes it as clear as can be done at this time that it is abandoned. I'm well aware that Composer itself won't care, but at least it's documented in the composer.json file now. 

Again, as I've said multiple times, I would _love_ to have this properly marked as abandoned, but it is impossible for _me_ to do so.
