### ISSUE TITLE
can't read cron expressions for 6 positions

### ISSUE THREAD

**Issue by roony4** [mtdowling/cron-expression#175]
I want to convert cron values to human readable format.I have cron values that have 6 positions.these are the examples..

`00 01 05 * * ?`

`$cron = Cron\CronExpression::factory('0 0 0 ? 1/2 FRI#2 *');
echo $cron->getNextRunDate()->format('Y-m-d H:i:s');`

error>>>
`Invalid CRON field value 0 at position 2`

how can I solve this.?

**Comment by dragonmantank** [comment]
Hello @roony4 !

This package is no longer being worked on, and has moved over to https://github.com/dragonmantank/cron-expression. If possible, please upgrade to the newest version of dragonmantank/cron-expression.

"Position 2" is actually the third slot (an error that is clearer in newer versions), and is the slot for "Day of Month." That number must be between 1 and 31. 0 is not a valid option.
