### ISSUE TITLE
abandoned package is required

### ISSUE THREAD

**Issue by baukezwaan** [mtdowling/cron-expression#178]
In composer a module is required **mtdowling/cron-expression**. This module seems to be abandoned (use dragonmantank/cron-expression instead). 

`Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.`

But I actually can't find any use in their code in this module?

**Comment by dragonmantank** [comment]
You can check your `composer.lock` file file and see which exact package depends on this package. If you figure it out, let me know and I will see if I can submit a PR to let them know to migrate.

**Comment by baukezwaan** [comment]
Sorry... this was indeed not intended to be raised as an issue overhere! My bad!
