### ISSUE TITLE
Memory leaks with Opcache

### ISSUE THREAD

**Issue by 0xTryCatch** [mtdowling/cron-expression#50]
In PHP 5.5 with the builtin Opcache enabled for the CLI using the CronExpression causes memory leaks.

```opcache.enable_cli = 1```

Execute the following script on the command line:

```
use Cron\CronExpression;

$expression = CronExpression::factory('25 0 1 * *');

while (true) {
    $expression->isDue();

    usleep(100000);
}
```

The used memory (RSS) will increase rapidly and PHP will eventually throw a fatal error.

Please note that when changing the expression to <code>* * * * *</code> this issue does not occur.

It may very well be an issue with the Opcache, however I haven't been able to pinpoint exactly what is happening here.

Tested on CentOS 6.4 and Mac OS X 10.9.2 with PHP 5.5.10 and PHP 5.5.11

**Comment by 0xTryCatch** [comment]
Fix released by PHP:

http://php.net/ChangeLog-5.php#5.6.5
http://php.net/ChangeLog-5.php#5.5.21

**Comment by mtdowling** [comment]
With this fixed in PHP, I think this can be closed.
