### ISSUE TITLE
Issue with cron

### ISSUE THREAD

**Issue by ap-aravind** [mtdowling/cron-expression#55]
Hi ,
    I am from India and my Timezone is UTC +5:30

   now the problem that arises to me is that assume the cron entry is "25 0 * * *"

   the time now say is 2014-05-13 17:19:00 
   so the next run time is 2014-05-14 00:25:00

in first loop obviously 0 doesn't match with 17 so the 17 is incremented .. 
  but here is the issue .. as we are converting to UTC and back .. after increment the time changes to .2014-05-13 17:30:00 notice that the minute is now 30 which is greater than 25.

  after the increments are as follows
2014-05-13 17:30:00
2014-05-13 18:30:00
2014-05-13 19:30:00
2014-05-13 20:30:00
2014-05-13 21:30:00
2014-05-13 22:30:00
2014-05-13 23:30:00
2014-05-14 00:30:00

And here the cron expression has been completely missed out and the system gets into an infinite loop

for the time being I have removed the covert to UTC and back feature as we don't need to deal with DST

**Comment by aGervais** [comment]
Having the same issue here with a Laravel 4 app at work; the "Temporary Fix" also prevents the exception however will not work for us as we may have users on non-hourly offsetted timezones which also support DST.

**Comment by fucongcong** [comment]
I set the timezones with 'PRC',it throws RuntimeException.but the UTC is ok.why?

**Comment by mtdowling** [comment]
Should be fixed in https://github.com/mtdowling/cron-expression/issues/92
