### ISSUE TITLE
getMultipleRunDates fails with bigger $total values

### ISSUE THREAD

**Issue by tuomassalo** [mtdowling/cron-expression#66]
This works:

    $cron=Cron\CronExpression::factory("0 0 * * *");
    $cron->getMultipleRunDates(12, "2008-11-09 00:00:00");

This fails:

    $cron=Cron\CronExpression::factory("0 0 * * *");
    $cron->getMultipleRunDates(13, "2008-11-09 00:00:00");

with error:

    [04-Nov-2014 09:51:22 Europe/Berlin] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Impossible CRON expression' in .../mtdowling/cron-expression/src/Cron/CronExpression.php:321
    Stack trace:
      #0 .../mtdowling/cron-expression/src/Cron/CronExpression.php(192): Cron\CronExpression->getRunDate('2008-11-09 00:0...', 12, false, false)
      #1 Command line code(1): Cron\CronExpression->getMultipleRunDates(13, '2008-11-09 00:0...')
      #2 {main}
      thrown in .../mtdowling/cron-expression/src/Cron/CronExpression.php on line 321

The same error happens with different values of `$total` depending on the cron expression.

**Comment by webpunk** [comment]
Just ran into the same problem. Is there any workaround?

**Comment by webpunk** [comment]
Okay. Probably not the best solutions but should be enough for a workaround:

    $rd = null;
    $rds = array();
    for ($i = 0; $i < 50; $i++) {
        $rd = $cron->getNextRunDate($rd);
        $rds[] = $rd;	            	
    }

After this $rds is an array which contains the next 50 run dates.

**Comment by gaomd** [comment]
@webpunk Your workaround is exactly what [getMultipleRunDates](https://github.com/mtdowling/cron-expression/blob/v1.0.4/src/Cron/CronExpression.php#L171-L190) method does, so it should fail, too.

One could increase the brute-force hard limit to workaround this exception, just go ahead and increase `1000` to any bigger value you would like in [src/Cron/CronExpression.php](https://github.com/mtdowling/cron-expression/blob/v1.0.4/src/Cron/CronExpression.php#L294).

**Comment by dragonmantank** [comment]
Can you re-test this with v1.1.0? I just tested locally and this seems to have cleared up this issue.

**Comment by dragonmantank** [comment]
Closing since 1.1.0 seems to have cleared this up, and haven't heard anything back.
