### ISSUE TITLE
Validate full cron command (with time and command itself)

### ISSUE THREAD

**Issue by huglester** [mtdowling/cron-expression#73]
Hello,

is it possible to provide, for example, full cron command like:
```bash
*       15-23   *       *       *       wget http://example.com
```
and later, for example I ->getMinutes(); ->getMonth(), ->getCommand() ?

because going threw source I did not find such functionality..

Thank you!

**Comment by mtdowling** [comment]
This library does not do this sort of thing. This library is only about parsing and checking cron expressions against a given date. There is no crontab handling.
