### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mnapoli** [mtdowling/cron-expression#74]
Hi there, this looks awesome and I'm considering using it for [piwik](https://github.com/piwik/piwik) but it looks like the last release is a year old (51 commits behind master).

Is that possible to tag a new release?

If it helps getting there faster, here is the changelog:

- Avoid infinity loop & division by zero #67
- Fix getRunDate() shouldn't modify currentTime parameter #57
- Missing anchors in regexp #63
- Avoid annotation parsing by Doctrine #62
- Optimization #52
- Fixed #20 Weekday-Hash for Saturday and Sunday doesn't seem to work #53
- Different timezone support #48
- Fixed regexp for day of week #49
- Set $currentTime as 'now' #36

I kept only the changes meaningful for end-users (e.g. not changes about tests or docs).

**Comment by mtdowling** [comment]
Thanks! I've tagged 1.0.4, and I'll use your changelog in the release.

**Comment by mnapoli** [comment]
:+1: thanks!

**Comment by GrahamCampbell** [comment]
It should have really been 1.1.0 given the new stuff. Patch releases are meant to have bug fixes only.

**Comment by mnapoli** [comment]
@GrahamCampbell I don't see a change that is not a bugfix or optimization, what do you mean by "new stuff"?

**Comment by GrahamCampbell** [comment]
https://github.com/mtdowling/cron-expression/pull/48 is not really a bug fix. It's really a new feature.

**Comment by mtdowling** [comment]
I thought that was a bug fix. Why do you think it's a feature?
