### ISSUE TITLE
Get the Cron Expression from database

### ISSUE THREAD

**Issue by thomas1216** [mtdowling/cron-expression#84]
Is possible get the Cron Expression be read from Database?, instead of using static cron expression, this will keep it flexible so if i  change the cron expression in the databse, i dont have to modified the file with the new cron expression.

// Works with predefined scheduling definitions
$cron = Cron\CronExpression::factory('* * * * *');
$cron->isDue();
echo $cron->getNextRunDate()->format('Y-m-d H:i:s');
echo $cron->getPreviousRunDate()->format('Y-m-d H:i:s');

**Comment by fruitl00p** [comment]
@thomas1216 you already asked something like this: #80

**Comment by mtdowling** [comment]
Yes, it is possible. Simply query the database, retrieve the cron expression, and provide it to the factory method as a string.

**Comment by thomas1216** [comment]
Its Possible use the Cron Expression work with Dynamic SQL? I need to Create Schedules on the fly, without modifying the Php File. or its a better solution. thanks
