### ISSUE TITLE
Colliding Cron Jobs

### ISSUE THREAD

**Issue by bentinata** [mtdowling/cron-expression#90]
Would it be possible to make a function that check colliding schedule?
Ex: `*/7 * * * *` and `*/3 * * * *` would collide at `21 * * * *`.

Alternatively, generating cron jobs would make it easier.
Ex: `*/25 * * * *` would generate `25 * * * *` and `50 * * * *`.
`12,40,55 * * * *` would generate `12 * * * *`, `40 * * * *`, `55 * * * *`.
(Or maybe more detailed to some extent?)

**Comment by mtdowling** [comment]
Sorry. This is out of scope for this library.
