### ISSUE TITLE
"Impossible cron expression" thrown when number of run dates > 16

### ISSUE THREAD

**Issue by majkelo** [mtdowling/cron-expression#99]
Even if I set **$which<30** I only get 16 results (instead of 30)before I get an error. 
Sample code:

	<?php
	include( './vendor/autoload.php');

		$cron = Cron\CronExpression::factory('0 10-20/2 * * 1-5 *');
		$eventDates = array();
		for ($which = 0; $which<30; $which++) {
			try{
				$nextDateOfEvent = $cron->getRunDate('now', $which)->format('Y-m-d H:i:s');
			}
			catch (RuntimeException $e) {
				//var_dump($e);
				break;
			}
			array_push($eventDates, $nextDateOfEvent);
		}
		var_dump($eventDates);
		exit();

	?>

**Comment by majkelo** [comment]
Moreover if I change CronExpression to **'49 10-20/2 * * 1-5 *'** I've got only 15 results.

If I change CronExpression to **'* 10-20/2 * * 1-5 *'** it works fine!

**Comment by dragonmantank** [comment]
Can you test this using v1.1.0, and changing `getRunDate()` to `getNextRunDate()`? I just tested this locally and was able to get as many runs as whatever `$which<` was set to.

**Comment by dragonmantank** [comment]
Closing since I haven't heard anything, and the new 1.1.0 release seems to have fixed it locally.
